
library(readr)
TS_data <- read_csv("TS_data.txt")
TS_data$DATE <- as.character(TS_data$DATE)
TS_data$DATE <- as.Date(TS_data$DATE, format = '%Y%m%d')
library(tidyverse)
df <- TS_data %>% select(TG, DATE) %>% rename(ds=DATE, y=TG) %>% filter(ds >= "1955-01-01")
library(prophet)
m <- prophet(df)
future <- make_future_dataframe(m, periods = 365)
tail(future)
forecast <- predict(m, future)
tail(forecast[c('ds', 'yhat', 'yhat_lower', 'yhat_upper')])
plot(m, forecast)
prophet_plot_components(m, forecast)
